### ISSUE TITLE
Using Tiff frames as input?

### ISSUE THREAD

**Issue by msoheib** [CaliAli-PV/CaliAli#1]
Hi, it is possible to use tiff frames for a recording session or is .h5 the only format currently supported?

**Comment by vergaloy** [comment]
Hi, at the moment, CaliAli is compatible only with .h5 files. However, I've just added a function that allows you to transform tiff files into .h5 format. To do this, execute "Downsample_tiff(1)" and select the tiff files you wish to convert.

Additionally, if you want to modify the downsampling factor, you can adjust the 'ds_f' value in the command: Downsample_tiff(ds_f, outpath, theFiles).

**Comment by vergaloy** [comment]
Multi-frame TIFF. I hope it helps you!
